### ISSUE TITLE
Pex command issues

### ISSUE THREAD

**Issue by mkg20001** [ZeroNetJS/zeronet-js#31]
**OS:** Linux

**Bundle:** Git

**Steps to Reproduce:**

 1. Forward the fileserver port
 2. Let your node running and add some zites via ui
 3. Wait for pex requests to come in

**Affected Component(s):** protocol 

**Expected Results:**

Pex should display peers in ip:port arrays

**Actual Results:**

Peers get display as `[ 'NaN.NaN.NaN.NaN:NaN' ]`

**Other information:**
```
  zeronet:protocol:client got   request => /ip4/175.101.88.223/tcp/55103 pex need=5, peers=["%\u0017��Q<","3\u000f3Q<"], site="12FLtEHXP6R3GRipPxSjusRH2S2aT2cbaM", peers_onion=["G������\u0006E>Q<"] +130ms
Got peers [ 'NaN.NaN.NaN.NaN:NaN', 'NaN.NaN.NaN.NaN:NaN' ]
```

Possibly encoding issue

Branch target/loading-zites

**Comment by mkg20001** [comment]
[debug.txt](https://github.com/ZeroNetJS/zeronet-js/files/1170076/debug.txt)
Hope the log contains some more clues

**Comment by Plasmmer** [comment]
I suggest you to create a site and accept BTC dons, so you can create bounties in Bountysource.

**Comment by mkg20001** [comment]
Why? With some hard work and some time every bug can be solved.
Also this project isn't big enough to do bounties. Maybe I think about that again in about 800 commits from now.

**Comment by Plasmmer** [comment]
The bounties are for it, to make good small projects into amazing great projects.
