### ISSUE TITLE
Windows testing

### ISSUE THREAD

**Issue by kustomzone** [ZeroNetJS/zeronet-js#4]
hi, bot@zeroid here. good work dude! tried your exe on win10 & win7 but it links to missing folders. (crash)

also has issue with bunyan... "_On Windows bunyan isn't recognized in the console as a program but as a command. So to invoke it the use of cmd was needed. I also had to install bunyan globally so that the console could access it._" ...so disabled the logging and it works. (example below)

```
if (!/^win/.test(process.platform)) { // linux
    var sp = spawn('bunyan', ['-o', 'short'], {
        stdio: [null, process.stdout, process.stderr]
    });
} else { // windows
    var sp = spawn('cmd', ['/s', '/c', 'bunyan', '-o', 'short'], {
        stdio: [null, process.stdout, process.stderr]
    });
}
```
done small update... "disable bunyan logging for windoze, skip favicon.ico, Zite & addZite = newZite, random nonce." ...but won't PR until working better etc.

https://github.com/kustomzone/zeronet-js

**Comment by mkg20001** [comment]
Actually wanted to ask you if you want to join the org, but your email seems broken.
Do you?

**Comment by kustomzone** [comment]
sure thanks!

(yeh, my hosting mail account shut as i move away from traditional hosting provider)

**Comment by mkg20001** [comment]
Nice! Just visit https://github.com/ZeroNetJS to accept the invitation.

**Comment by mkg20001** [comment]
I added some scripts and appveyor but as I haven't used windows for ages they don't work.
Basically the scripts/install.sh script needs to be ported to .bat and the cmd command in appveyor.yml doesn't work

**Comment by mkg20001** [comment]
Also I prefer to have a way to chat instead of (ab)using the github issues for that.
Tox? mkg20001@toxme.io

**Comment by kustomzone** [comment]
bunyan logging error fixed as of commit 135 -> 6a1bddd78d845dc1b00c5cc9e60e7fb18e3cbe0b

**Comment by mkg20001** [comment]
Windows testing in ci was added in v0.0.1-alpha14

**Comment by Plasmmer** [comment]
@mkg20001
I use Windows. Do you need something?

**Comment by kustomzone** [comment]
'''
set DEBUG_PACKETS=1
set DEBUG=* node zeronet.js
npm start
'''

**Comment by Plasmmer** [comment]
Please say more details.

**Comment by mkg20001** [comment]
It's the stuff you need to run.
Or more specifically:
```
cmd /C .\scripts\install.cmd
set DEBUG=*
set DEBUG_PACKETS=1
npm test
npm start
```

Then play arround with the node. Note that ui still does nothing as #29 still is WIP

**Comment by mkg20001** [comment]
I've added automatic windows testing. @kustomzone @Plasmmer closing?

**Comment by Plasmmer** [comment]
Ok.
