### ISSUE TITLE
Lower the peers score by 20 every time an error response is returned

### ISSUE THREAD

**Issue by Plasmmer** [ZeroNetJS/zeronet-js#46]

**Comment by Plasmmer** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/1016.

**Comment by Plasmmer** [comment]
Also, automatically change to another peer when a peer is sending the site with missing files.

**Comment by Plasmmer** [comment]
Reference: https://github.com/HelloZeroNet/ZeroNet/issues/1036.

**Comment by mkg20001** [comment]
> Also, automatically change to another peer when a peer is sending the site with missing files.

This is already being done [here](https://github.com/ZeroNetJS/zeronet-js/blob/master/zeronet-zite/lib/file/stream.js#L53)

> Automatically block peers that are returning 404

Instead we could use a peer score system and lower the peers score by 20 every time an error response is returned.
Peers with less then -100 points will be blocked then

**Comment by Plasmmer** [comment]
But if the peer use the same Tor IP of others, then all users of a relay will be blocked?

**Comment by Plasmmer** [comment]
@mkg20001

**Comment by mkg20001** [comment]
> But if the peer use the same Tor IP of others, then all users of a relay will be blocked?

You can't expose your ip via a tor exit node.
Additionally the client would only block the onion address not the relays in between.

**Comment by Plasmmer** [comment]
I'd updated the title.

**Comment by Plasmmer** [comment]
Amazing.
I updated the title of this issue.

**Comment by mkg20001** [comment]
I will fix this during the rewrite of the discovery stuff, etc. See #91
