### ISSUE TITLE
"project" GitHub label

### ISSUE THREAD

**Issue by Plasmmer** [ZeroNetJS/zeronet-js#62]
For issues related to the project, like about .mds, etc.

**Comment by mkg20001** [comment]
I don't understand what benefits we gain from this new label.
All issues are supposed to be project related/on-topic

**Comment by Plasmmer** [comment]
I'm not talking about the code of the platform app, but about the project.

**Comment by mkg20001** [comment]
Do you mean something similar to "meta issues"?

**Comment by Plasmmer** [comment]
Yes.

**Comment by mkg20001** [comment]
Added
