### ISSUE TITLE
Let's create the Stage 4?

### ISSUE THREAD

**Issue by Plasmmer** [ZeroNetJS/zeronet-js#73]

**Comment by mkg20001** [comment]
Or just a new milestone "Future"?

**Comment by Plasmmer** [comment]
You can move the priority issues of future to the Stage 4, and the others to the Future.

**Comment by mkg20001** [comment]
It will take at least 5 months to finish stage 1-3 so that might not be a good idea

**Comment by Plasmmer** [comment]
Stage 4 could have: #41, #26, #22, #20, #21, #40.
